/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/chalice.glb --transform 
Files: public/chalice.glb [14.14KB] > /Users/david.malinen/Documents/EGERY/dev/vkkng/chalice-transformed.glb [3.98KB] (72%)
*/

import { useGLTF } from '@react-three/drei'

export function Chalice(props) {
  const { nodes, materials } = useGLTF('/chalice-transformed.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dragon_chalice.geometry} material={materials.Obsidian} position={[-12.624, 6.324, 0.933]} rotation={[-1.555, 0, -Math.PI]} scale={0.009} />
    </group>
  )
}

useGLTF.preload('/chalice-transformed.glb')
