/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/hermes_staff_parents_groups.glb --transform 
Files: public/hermes_staff_parents_groups.glb [117.38KB] > /Users/david.malinen/Documents/EGERY/dev/vkkng/hermes_staff_parents_groups-transformed.glb [15.65KB] (87%)
*/

import { useGLTF } from '@react-three/drei'
import type { ReactElement } from 'react';

interface HermesStaffProps {
  [key: string]: any;
}

export function HermesStaff(props: HermesStaffProps): ReactElement {
  const { nodes, materials } = useGLTF('/hermes_staff_parents_groups-transformed.glb') as any;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.hermes_staff_parent_groups.geometry} material={materials['Obsidian.002']} position={[-5.359, 6.129, -6.723]} rotation={[-1.49, -0.379, 0.41]} />
    </group>
  )
}

useGLTF.preload('/hermes_staff_parents_groups-transformed.glb')
